# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Feedback.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import requests
from PyQt5 import QtCore, QtGui, QtWidgets
from my_header import HeaderWidget

from PyQt5.QtCore import QDate

class Ui_Feedbackwindow(QtWidgets.QWidget):
    def __init__(self,window):
        super().__init__()
        self.main_window=window
        self.selected_file_path = None
        self.setupUi()


    def go_back(self):
        self.main_window.showDashboard()

    def submit_feedback(self):
        feedback=self.feedbackfield.text()
        url='https://abidali1999063.pythonanywhere.com/feedback'
        try: email=self.main_window.userid
        except: email='boota@gmail.com'
        # date='12523'
        date = QDate.currentDate().toString("dd/MM/yyyy")

        print(date)
        data={'email':email,'comment':feedback,'date':date}
        r=requests.post(url,json=data)
        print(r.text)
        print(r.status_code)
        if r.status_code==201: QtWidgets.QMessageBox.information(self, 'Received', 'Your Feedback has been recieved')
        else: QtWidgets.QMessageBox.information(self, 'Try again', f'Something went wrong {r.status_code} {r.text}')



    def setupUi(self):
        # Feedbackwindow.setObjectName("Feedbackwindow")
        self.centralwidget = QtWidgets.QWidget(self)
        self.resize(1096, 900)
        # self.centralwidget.setStyleSheet("background:white !important;")
        self.header=HeaderWidget(self.main_window,self.centralwidget)
#         self.label = QtWidgets.QLabel(self.centralwidget)
#         self.label.setGeometry(QtCore.QRect(0, -10, 151, 121))
#         self.label.setStyleSheet("image:url(:/newPrefix/images/Malx logo.png);\n"
# "background-size:cover !important;\n"
# "background-repeat:no-repeat !important;\n"
# "text-align:center !important;\n"
# "margin:0px auto !important;")
#         self.label.setText("")
#         self.label.setObjectName("label")
#         self.pushButton = QtWidgets.QPushButton(self.centralwidget)
#         self.pushButton.setGeometry(QtCore.QRect(480, 30, 230, 41))
#         self.pushButton.setStyleSheet("background:black;\n"
# "color:#fff;\n"
# "border:1px solid black;\n"
# "font-weight:bold;\n"
# "font-size:14px;")
#         self.pushButton.setObjectName("pushButton")
#         self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
#         self.pushButton_2.setGeometry(QtCore.QRect(740, 30, 121, 41))
#         self.pushButton_2.setStyleSheet("background:white;\n"
# "color:#00000;\n"
# "border:1px solid black;\n"
# "font-weight:bold;\n"
# "font-size:14px;")
#         self.pushButton_2.setObjectName("pushButton_2")
#         self.label_2 = QtWidgets.QLabel(self.centralwidget)
#         self.label_2.setGeometry(QtCore.QRect(860, 0, 101, 91))
#         self.label_2.setStyleSheet("image:url(:/newPrefix/images/user.png);\n"
# "background-size:cover !important;\n"
# "background-repeat:no-repeat !important;\n"
# "text-align:center !important;\n"
# "margin:0px auto !important;")
#         self.label_2.setText("")
#         self.label_2.setObjectName("label_2")
#         self.label_3 = QtWidgets.QLabel(self.centralwidget)
#         self.label_3.setGeometry(QtCore.QRect(910, 0, 101, 91))
#         self.label_3.setStyleSheet("image:url(:/newPrefix/images/bell.png);\n"
# "background-size:cover !important;\n"
# "background-repeat:no-repeat !important;\n"
# "text-align:center !important;\n"
# "margin:0px auto !important;")
#         self.label_3.setText("")
#         self.label_3.setObjectName("label_3")
#         self.label_4 = QtWidgets.QLabel(self.centralwidget)
#         self.label_4.setGeometry(QtCore.QRect(960, 0, 101, 91))
#         self.label_4.setStyleSheet("image:url(:/newPrefix/images/settings.png);\n"
# "background-size:cover !important;\n"
# "background-repeat:no-repeat !important;\n"
# "text-align:center !important;\n"
# "margin:0px auto !important;")
#         self.label_4.setText("")
#         self.label_4.setObjectName("label_4")
#         self.label_5 = QtWidgets.QLabel(self.centralwidget)
#         self.label_5.setGeometry(QtCore.QRect(1010, 0, 101, 91))
#         self.label_5.setStyleSheet("image:url(:/newPrefix/images/question.png);\n"
# "background-size:cover !important;\n"
# "background-repeat:no-repeat !important;\n"
# "text-align:center !important;\n"
# "margin:0px auto !important;")
#         self.label_5.setText("")
#         self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(310, 120, 601, 131))
        self.label_7.setStyleSheet("font-size:25px;\n"
"font-weight:bold;\n"
"line-height:40px;\n"
"margin:0px auto !important;\n"
"")
        self.label_7.setObjectName("label_7")
        # self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        # self.horizontalSlider.setGeometry(QtCore.QRect(-10, 90, 1111, 20))
        # self.horizontalSlider.setStyleSheet("color:rgb(0, 0, 0);")
        # self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        # self.horizontalSlider.setObjectName("horizontalSlider")
        self.feedbackfield = QtWidgets.QLineEdit(self.centralwidget)
        self.feedbackfield.setGeometry(QtCore.QRect(230, 450, 721, 191))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.feedbackfield.setFont(font)
        self.feedbackfield.setStyleSheet("border:1px solid black;")
        self.feedbackfield.setObjectName("feedbackfield")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(370, 690, 141, 41))
        self.pushButton_3.setStyleSheet("background:black;\n"
"color:#fff;\n"
"border:1px solid black;\n"
"font-weight:bold;\n"
"font-size:14px;")
        self.pushButton_3.setObjectName("pushButton_3")

        self.pushButton_3.clicked.connect(self.go_back)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(620, 690, 121, 41))
        self.pushButton_4.setStyleSheet("background:white;\n"
"color:#00000;\n"
"border:1px solid black;\n"
"font-weight:bold;\n"
"font-size:14px;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.submit_feedback)



        # self.Emailfield = QtWidgets.QLineEdit(self.centralwidget)
        # self.Emailfield.setGeometry(QtCore.QRect(230, 310, 721, 41))
        # font = QtGui.QFont()
        # font.setPointSize(11)
        # self.Emailfield.setFont(font)
        # self.Emailfield.setStyleSheet("border:1px solid black;")
        # self.Emailfield.setObjectName("Emailfield")
        # self.Datefield = QtWidgets.QLineEdit(self.centralwidget)
        # self.Datefield.setGeometry(QtCore.QRect(230, 380, 721, 41))
        # font = QtGui.QFont()
        # font.setPointSize(11)
        # self.Datefield.setFont(font)
        # self.Datefield.setStyleSheet("border:1px solid black;")
        # self.Datefield.setObjectName("Datefield")
        # Feedbackwindow.setCentralWidget(self.centralwidget)
        # self.menubar = QtWidgets.QMenuBar(Feedbackwindow)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 1096, 22))
        # self.menubar.setObjectName("menubar")
        # Feedbackwindow.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(Feedbackwindow)
        # self.statusbar.setObjectName("statusbar")
        # Feedbackwindow.setStatusBar(self.statusbar)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, Feedbackwindow):
        _translate = QtCore.QCoreApplication.translate
        Feedbackwindow.setWindowTitle(_translate("Feedbackwindow", "MainWindow"))
        # self.pushButton.setText(_translate("Feedbackwindow", "ACTIVATE SUBSCRIPTION"))
        # self.pushButton_2.setText(_translate("Feedbackwindow", "BUY NOW"))
        self.label_7.setText(_translate("Feedbackwindow", "PROVIDE YOUR FEEDBACK, \n"
"YOUR FEEDBACK IS IMPORTANT FOR US "))
        self.feedbackfield.setPlaceholderText(_translate("Feedbackwindow", "Your Feedback"))
        self.pushButton_3.setText(_translate("Feedbackwindow", "CANCEL"))
        self.pushButton_4.setText(_translate("Feedbackwindow", "SUBMIT"))
        # self.Emailfield.setPlaceholderText(_translate("Feedbackwindow", "Email"))
        # self.Datefield.setPlaceholderText(_translate("Feedbackwindow", "Date"))
from qrc import source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    # Feedbackwindow = QtWidgets.QMainWindow()
    ui = Ui_Feedbackwindow(app)
    # ui.setupUi(Feedbackwindow)
    # Feedbackwindow.resize(1100,900)
    ui.show()
    sys.exit(app.exec_())
