# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Help.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from my_header import HeaderWidget


class Ui_Helpwindow(QtWidgets.QWidget):
    def __init__(self,window):
        super().__init__()
        self.main_window=window
        self.selected_file_path = None
        self.setupUi()

    def setupUi(self):
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.resize(1096, 902)
        # self.centralwidget.setStyleSheet("background:white !important;")
        self.header=HeaderWidget(self.main_window,self.centralwidget)

        # self.centralwidget = QtWidgets.QWidget(Helpwindow)
        # self.centralwidget.setObjectName("centralwidget")
#         self.label = QtWidgets.QLabel(self.centralwidget)
#         self.label.setGeometry(QtCore.QRect(0, -10, 151, 121))
#         self.label.setStyleSheet("image:url(:/newPrefix/images/Malx logo.png);\n"
# "background-size:cover !important;\n"
# "background-repeat:no-repeat !important;\n"
# "text-align:center !important;\n"
# "margin:0px auto !important;")
#         self.label.setText("")
#         self.label.setObjectName("label")
#         self.pushButton = QtWidgets.QPushButton(self.centralwidget)
#         self.pushButton.setGeometry(QtCore.QRect(480, 30, 230, 41))
#         self.pushButton.setStyleSheet("background:black;\n"
# "color:#fff;\n"
# "border:1px solid black;\n"
# "font-weight:bold;\n"
# "font-size:14px;")
#         self.pushButton.setObjectName("pushButton")
#         self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
#         self.pushButton_2.setGeometry(QtCore.QRect(740, 30, 121, 41))
#         self.pushButton_2.setStyleSheet("background:white;\n"
# "color:#00000;\n"
# "border:1px solid black;\n"
# "font-weight:bold;\n"
# "font-size:14px;")
#         self.pushButton_2.setObjectName("pushButton_2")
#         self.label_2 = QtWidgets.QLabel(self.centralwidget)
#         self.label_2.setGeometry(QtCore.QRect(860, 0, 101, 91))
#         self.label_2.setStyleSheet("image:url(:/newPrefix/images/user.png);\n"
# "background-size:cover !important;\n"
# "background-repeat:no-repeat !important;\n"
# "text-align:center !important;\n"
# "margin:0px auto !important;")
#         self.label_2.setText("")
#         self.label_2.setObjectName("label_2")
#         self.label_3 = QtWidgets.QLabel(self.centralwidget)
#         self.label_3.setGeometry(QtCore.QRect(910, 0, 101, 91))
#         self.label_3.setStyleSheet("image:url(:/newPrefix/images/bell.png);\n"
# "background-size:cover !important;\n"
# "background-repeat:no-repeat !important;\n"
# "text-align:center !important;\n"
# "margin:0px auto !important;")
#         self.label_3.setText("")
#         self.label_3.setObjectName("label_3")
#         self.label_4 = QtWidgets.QLabel(self.centralwidget)
#         self.label_4.setGeometry(QtCore.QRect(960, 0, 101, 91))
#         self.label_4.setStyleSheet("image:url(:/newPrefix/images/settings.png);\n"
# "background-size:cover !important;\n"
# "background-repeat:no-repeat !important;\n"
# "text-align:center !important;\n"
# "margin:0px auto !important;")
#         self.label_4.setText("")
#         self.label_4.setObjectName("label_4")
#         self.label_5 = QtWidgets.QLabel(self.centralwidget)
#         self.label_5.setGeometry(QtCore.QRect(1010, 0, 101, 91))
#         self.label_5.setStyleSheet("image:url(:/newPrefix/images/question.png);\n"
# "background-size:cover !important;\n"
# "background-repeat:no-repeat !important;\n"
# "text-align:center !important;\n"
# "margin:0px auto !important;")
#         self.label_5.setText("")
#         self.label_5.setObjectName("label_5")
#         self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
#         self.horizontalSlider.setGeometry(QtCore.QRect(-10, 90, 1111, 20))
#         self.horizontalSlider.setStyleSheet("color:rgb(0, 0, 0);")
#         self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
#         self.horizontalSlider.setObjectName("horizontalSlider")
        self.Helpframe = QtWidgets.QFrame(self.centralwidget)
        self.Helpframe.setGeometry(QtCore.QRect(0, 100, 1101, 61))
        self.Helpframe.setStyleSheet("background:#D6D6D6;")
        self.Helpframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Helpframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Helpframe.setObjectName("Helpframe")
        self.Helpheading = QtWidgets.QLabel(self.Helpframe)
        self.Helpheading.setGeometry(QtCore.QRect(0, 10, 151, 51))
        self.Helpheading.setStyleSheet("font-size:20px;\n"
"font-weight:bold;\n"
"line-height:40px;\n"
"margin:0px auto !important;\n"
"")
        self.Helpheading.setObjectName("Helpheading")
        self.Helpframe_2 = QtWidgets.QFrame(self.centralwidget)
        self.Helpframe_2.setGeometry(QtCore.QRect(10, 220, 451, 141))
        self.Helpframe_2.setStyleSheet("background:#D6D6D6;")
        self.Helpframe_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Helpframe_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Helpframe_2.setObjectName("Helpframe_2")
        self.label_6 = QtWidgets.QLabel(self.Helpframe_2)
        self.label_6.setGeometry(QtCore.QRect(0, 20, 121, 101))
        self.label_6.setStyleSheet("image:url(:/newPrefix/images/guide.png);\n"
"background-size:cover !important;\n"
"background-repeat:no-repeat !important;\n"
"text-align:center !important;\n"
"margin:0px auto !important;")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.Helpframe_2)
        self.label_7.setGeometry(QtCore.QRect(80, 20, 251, 51))
        self.label_7.setStyleSheet("font-size:18px;\n"
"font-weight:bold;\n"
"line-height:40px;\n"
"margin:0px auto !important;\n"
"")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.Helpframe_2)
        self.label_8.setGeometry(QtCore.QRect(80, 60, 311, 51))
        self.label_8.setStyleSheet("font-size:13px;\n"
"line-height:40px;\n"
"margin:0px auto !important;\n"
"")
        self.label_8.setObjectName("label_8")
        self.Helpframe_3 = QtWidgets.QFrame(self.centralwidget)
        self.Helpframe_3.setGeometry(QtCore.QRect(630, 220, 451, 141))
        self.Helpframe_3.setStyleSheet("background:#D6D6D6;")
        self.Helpframe_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Helpframe_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Helpframe_3.setObjectName("Helpframe_3")
        self.label_9 = QtWidgets.QLabel(self.Helpframe_3)
        self.label_9.setGeometry(QtCore.QRect(0, 20, 121, 101))
        self.label_9.setStyleSheet("image:url(:/newPrefix/images/customercare.png);\n"
"background-size:cover !important;\n"
"background-repeat:no-repeat !important;\n"
"text-align:center !important;\n"
"margin:0px auto !important;")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.Helpframe_3)
        self.label_10.setGeometry(QtCore.QRect(80, 20, 251, 51))
        self.label_10.setStyleSheet("font-size:18px;\n"
"font-weight:bold;\n"
"line-height:40px;\n"
"margin:0px auto !important;\n"
"")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.Helpframe_3)
        self.label_11.setGeometry(QtCore.QRect(80, 60, 311, 51))
        self.label_11.setStyleSheet("font-size:13px;\n"
"line-height:40px;\n"
"margin:0px auto !important;\n"
"")
        self.label_11.setObjectName("label_11")
        self.Helpframe_4 = QtWidgets.QFrame(self.centralwidget)
        self.Helpframe_4.setGeometry(QtCore.QRect(10, 410, 451, 141))
        self.Helpframe_4.setStyleSheet("background:#D6D6D6;")
        self.Helpframe_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Helpframe_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Helpframe_4.setObjectName("Helpframe_4")
        self.label_12 = QtWidgets.QLabel(self.Helpframe_4)
        self.label_12.setGeometry(QtCore.QRect(0, 20, 121, 101))
        self.label_12.setStyleSheet("image:url(:/newPrefix/images/tools.png);\n"
"background-size:cover !important;\n"
"background-repeat:no-repeat !important;\n"
"text-align:center !important;\n"
"margin:0px auto !important;")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.Helpframe_4)
        self.label_13.setGeometry(QtCore.QRect(80, 20, 251, 51))
        self.label_13.setStyleSheet("font-size:18px;\n"
"font-weight:bold;\n"
"line-height:40px;\n"
"margin:0px auto !important;\n"
"")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.Helpframe_4)
        self.label_14.setGeometry(QtCore.QRect(80, 60, 321, 51))
        self.label_14.setStyleSheet("font-size:13px;\n"
"line-height:40px;\n"
"margin:0px auto !important;\n"
"")
        self.label_14.setObjectName("label_14")
        self.Helpheading_2 = QtWidgets.QLabel(self.centralwidget)
        self.Helpheading_2.setGeometry(QtCore.QRect(-20, 580, 151, 61))
        self.Helpheading_2.setStyleSheet("font-size:20px;\n"
"font-weight:bold;\n"
"line-height:40px;\n"
"margin:0px auto !important;\n"
"")
        self.Helpheading_2.setObjectName("Helpheading_2")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(-20, 620, 341, 61))
        self.label_15.setStyleSheet("font-size:13px;\n"
"line-height:40px;\n"
"margin:0px auto !important;\n"
"")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(-20, 660, 341, 41))
        self.label_16.setStyleSheet("font-size:13px;\n"
"line-height:40px;\n"
"margin:0px auto !important;\n"
"")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(-20, 690, 471, 41))
        self.label_17.setStyleSheet("font-size:13px;\n"
"line-height:40px;\n"
"margin:0px auto !important;\n"
"")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(-20, 730, 391, 31))
        self.label_18.setStyleSheet("font-size:13px;\n"
"line-height:40px;\n"
"margin:0px auto !important;\n"
"")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(-20, 760, 441, 41))
        self.label_19.setStyleSheet("font-size:13px;\n"
"line-height:40px;\n"
"margin:0px auto !important;\n"
"")
        self.label_19.setObjectName("label_19")
        # self.setCentralWidget(self.centralwidget)
        # self.menubar = QtWidgets.QMenuBar(Helpwindow)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 1096, 22))
        # self.menubar.setObjectName("menubar")
        # Helpwindow.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(Helpwindow)
        # self.statusbar.setObjectName("statusbar")
        # Helpwindow.setStatusBar(self.statusbar)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, Helpwindow):
        _translate = QtCore.QCoreApplication.translate
        Helpwindow.setWindowTitle(_translate("Helpwindow", "MainWindow"))
        # self.pushButton.setText(_translate("Helpwindow", "ACTIVATE SUBSCRIPTION"))
        # self.pushButton_2.setText(_translate("Helpwindow", "BUY NOW"))
        self.Helpheading.setText(_translate("Helpwindow", "HELP"))
        self.label_7.setText(_translate("Helpwindow", "MALX USER GUIDE"))
        self.label_8.setText(_translate("Helpwindow", "Read the offical instruction manual"))
        self.label_10.setText(_translate("Helpwindow", "MALX SUPPORT"))
        self.label_11.setText(_translate("Helpwindow", "Find answers and troubleshoot issues"))
        self.label_13.setText(_translate("Helpwindow", "SUPPORT TOOLS"))
        self.label_14.setText(_translate("Helpwindow", "Find and fix software issues automatically"))
        self.Helpheading_2.setText(_translate("Helpwindow", "FAQs"))
        self.label_15.setText(_translate("Helpwindow", "<a href='#'>How do I activate my Premium subscription?</a>\n"
""))
        self.label_16.setText(_translate("Helpwindow", "<a href='#'>How do I find my Premium license key?</a>\n"
""))
        self.label_17.setText(_translate("Helpwindow", "<a href='#'>How do I manage my premium subscription for all devices?</a>\n"
""))
        self.label_18.setText(_translate("Helpwindow", "<a href='#'>How do I stop MalX form altering on trusted items?</a>\n"
""))
        self.label_19.setText(_translate("Helpwindow", "<a href='#'>How do I buy additional licenses to protect all my devices?</a>"))

from qrc import source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    # Helpwindow = QtWidgets.QMainWindow()
    ui = Ui_Helpwindow(app)
    ui.show()
    sys.exit(app.exec_())
