# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from my_header import HeaderWidget
import requests
import hashlib

class Ui_settings(QtWidgets.QWidget):
    def __init__(self,window):
        super().__init__()
        self.main_window=window
        self.selected_file_path = None
        self.setupUi()

    def update_account(self):
        name=self.Emailfield.text().strip()
        email=self.Emailfield_2.text().strip()
        password = hashlib.sha256(self.Emailfield_4.text().strip().encode()).hexdigest()
        phone=self.Emailfield_6.text().strip()
        url='https://abidali1999063.pythonanywhere.com/update_account'
        try: oldemail=self.main_window.userid
        except: oldemail='waseem123@gmail.com'
        
        data={'old_email':oldemail,'name':name,'email':email,'password':password,'phone':phone}
        print(data)
        r=requests.post(url,json=data)
        print(r.text)
        print(r.status_code)
        if r.status_code==200: 
             QtWidgets.QMessageBox.information(self, 'Updated', 'Your profile has been updated')
             self.main_window.userid=email
        else: QtWidgets.QMessageBox.information(self, 'Try again', f'Something went wrong {r.status_code} {r.text}')



    def setupUi(self):
        self.centralwidget = QtWidgets.QWidget(self)
        # classificationwindow.setObjectName("classificationwindow")
        self.header=HeaderWidget(self.main_window,self.centralwidget)

        self.centralwidget.resize(1096, 916)
        # self.centralwidget.setStyleSheet("background:white !important;")
        # self.centralwidget = QtWidgets.QWidget(classificationwindow)
        # self.centralwidget.setObjectName("centralwidget")
#         self.label = QtWidgets.QLabel(self.centralwidget)
#         self.label.setGeometry(QtCore.QRect(0, -10, 151, 121))
#         self.label.setStyleSheet("image:url(:/newPrefix/images/Malx logo.png);\n"
# "background-size:cover !important;\n"
# "background-repeat:no-repeat !important;\n"
# "text-align:center !important;\n"
# "margin:0px auto !important;")
#         self.label.setText("")
#         self.label.setObjectName("label")
#         self.pushButton = QtWidgets.QPushButton(self.centralwidget)
#         self.pushButton.setGeometry(QtCore.QRect(480, 30, 230, 41))
#         self.pushButton.setStyleSheet("background:black;\n"
# "color:#fff;\n"
# "border:1px solid black;\n"
# "font-weight:bold;\n"
# "font-size:14px;")
#         self.pushButton.setObjectName("pushButton")
#         self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
#         self.pushButton_2.setGeometry(QtCore.QRect(740, 30, 121, 41))
#         self.pushButton_2.setStyleSheet("background:white;\n"
# "color:#00000;\n"
# "border:1px solid black;\n"
# "font-weight:bold;\n"
# "font-size:14px;")
#         self.pushButton_2.setObjectName("pushButton_2")
#         self.label_2 = QtWidgets.QLabel(self.centralwidget)
#         self.label_2.setGeometry(QtCore.QRect(860, 0, 101, 91))
#         self.label_2.setStyleSheet("image:url(:/newPrefix/images/user.png);\n"
# "background-size:cover !important;\n"
# "background-repeat:no-repeat !important;\n"
# "text-align:center !important;\n"
# "margin:0px auto !important;")
#         self.label_2.setText("")
#         self.label_2.setObjectName("label_2")
#         self.label_3 = QtWidgets.QLabel(self.centralwidget)
#         self.label_3.setGeometry(QtCore.QRect(910, 0, 101, 91))
#         self.label_3.setStyleSheet("image:url(:/newPrefix/images/bell.png);\n"
# "background-size:cover !important;\n"
# "background-repeat:no-repeat !important;\n"
# "text-align:center !important;\n"
# "margin:0px auto !important;")
#         self.label_3.setText("")
#         self.label_3.setObjectName("label_3")
#         self.label_4 = QtWidgets.QLabel(self.centralwidget)
#         self.label_4.setGeometry(QtCore.QRect(960, 0, 101, 91))
#         self.label_4.setStyleSheet("image:url(:/newPrefix/images/settings.png);\n"
# "background-size:cover !important;\n"
# "background-repeat:no-repeat !important;\n"
# "text-align:center !important;\n"
# "margin:0px auto !important;")
#         self.label_4.setText("")
#         self.label_4.setObjectName("label_4")
#         self.label_5 = QtWidgets.QLabel(self.centralwidget)
#         self.label_5.setGeometry(QtCore.QRect(1010, 0, 101, 91))
#         self.label_5.setStyleSheet("image:url(:/newPrefix/images/question.png);\n"
# "background-size:cover !important;\n"
# "background-repeat:no-repeat !important;\n"
# "text-align:center !important;\n"
# "margin:0px auto !important;")
#         self.label_5.setText("")
#         self.label_5.setObjectName("label_5")
#         self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
#         self.horizontalSlider.setGeometry(QtCore.QRect(-10, 90, 1111, 20))
#         self.horizontalSlider.setStyleSheet("color:rgb(0, 0, 0);")
#         self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
#         self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 130, 201, 51))
        self.label_7.setStyleSheet("font-size:20px;\n"
"font-weight:bold;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_7.setObjectName("label_7")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(150, 170, 1001, 721))
        self.tabWidget.setObjectName("tabWidget")
        self.General_3 = QtWidgets.QWidget()
        self.General_3.setObjectName("General_3")
        self.label_14 = QtWidgets.QLabel(self.General_3)
        self.label_14.setGeometry(QtCore.QRect(10, 20, 261, 51))
        self.label_14.setStyleSheet("font-size:18px;\n"
"font-weight:bold;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.General_3)
        self.label_15.setGeometry(QtCore.QRect(10, 60, 481, 51))
        self.label_15.setStyleSheet("font-size:14px;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_15.setObjectName("label_15")
        self.pushButton_5 = QtWidgets.QPushButton(self.General_3)
        self.pushButton_5.setGeometry(QtCore.QRect(50, 110, 161, 41))
        self.pushButton_5.setStyleSheet("background:white;\n"
"color:#00000;\n"
"border:1px solid black;\n"
"font-weight:bold;\n"
"font-size:14px;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.line_3 = QtWidgets.QFrame(self.General_3)
        self.line_3.setGeometry(QtCore.QRect(0, 180, 991, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_16 = QtWidgets.QLabel(self.General_3)
        self.label_16.setGeometry(QtCore.QRect(10, 200, 321, 51))
        self.label_16.setStyleSheet("font-size:18px;\n"
"font-weight:bold;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.General_3)
        self.label_17.setGeometry(QtCore.QRect(10, 240, 481, 51))
        self.label_17.setStyleSheet("font-size:14px;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_17.setObjectName("label_17")
        self.line_4 = QtWidgets.QFrame(self.General_3)
        self.line_4.setGeometry(QtCore.QRect(0, 310, 991, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_18 = QtWidgets.QLabel(self.General_3)
        self.label_18.setGeometry(QtCore.QRect(10, 330, 341, 51))
        self.label_18.setStyleSheet("font-size:18px;\n"
"font-weight:bold;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.General_3)
        self.label_19.setGeometry(QtCore.QRect(10, 380, 481, 51))
        self.label_19.setStyleSheet("font-size:14px;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.General_3)
        self.label_20.setGeometry(QtCore.QRect(10, 430, 341, 51))
        self.label_20.setStyleSheet("font-size:14px;\n"
"font-weight:bold;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_20.setObjectName("label_20")
        self.line_5 = QtWidgets.QFrame(self.General_3)
        self.line_5.setGeometry(QtCore.QRect(0, 470, 991, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_21 = QtWidgets.QLabel(self.General_3)
        self.label_21.setGeometry(QtCore.QRect(10, 490, 341, 51))
        self.label_21.setStyleSheet("font-size:18px;\n"
"font-weight:bold;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.General_3)
        self.label_22.setGeometry(QtCore.QRect(10, 540, 481, 51))
        self.label_22.setStyleSheet("font-size:14px;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_22.setObjectName("label_22")
        self.pushButton_6 = QtWidgets.QPushButton(self.General_3)
        self.pushButton_6.setGeometry(QtCore.QRect(50, 610, 191, 41))
        self.pushButton_6.setStyleSheet("background:white;\n"
"color:#00000;\n"
"border:1px solid black;\n"
"font-weight:bold;\n"
"font-size:14px;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.checkBox = QtWidgets.QCheckBox(self.General_3)
        self.checkBox.setGeometry(QtCore.QRect(820, 70, 70, 18))
        self.checkBox.setStyleSheet("QCheckBox::indicator{\n"
"  width:50px;\n"
"  height:50px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked{\n"
" image:url(:/newPrefix/images/switchon.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked{\n"
"  image:url(:/newPrefix/images/switchoff.png);\n"
"}")
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.tabWidget.addTab(self.General_3, "")
        self.Notifications_3 = QtWidgets.QWidget()
        self.Notifications_3.setObjectName("Notifications_3")
        self.label_23 = QtWidgets.QLabel(self.Notifications_3)
        self.label_23.setGeometry(QtCore.QRect(0, 10, 261, 51))
        self.label_23.setStyleSheet("font-size:18px;\n"
"font-weight:bold;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.Notifications_3)
        self.label_24.setGeometry(QtCore.QRect(0, 50, 481, 51))
        self.label_24.setStyleSheet("font-size:14px;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.Notifications_3)
        self.label_25.setGeometry(QtCore.QRect(0, 90, 481, 51))
        self.label_25.setStyleSheet("font-size:14px;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.Notifications_3)
        self.label_26.setGeometry(QtCore.QRect(0, 130, 841, 51))
        self.label_26.setStyleSheet("font-size:14px;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_26.setObjectName("label_26")
        self.comboBox = QtWidgets.QComboBox(self.Notifications_3)
        self.comboBox.setGeometry(QtCore.QRect(290, 180, 81, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_27 = QtWidgets.QLabel(self.Notifications_3)
        self.label_27.setGeometry(QtCore.QRect(0, 170, 311, 51))
        self.label_27.setStyleSheet("font-size:14px;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_27.setObjectName("label_27")
        self.line_6 = QtWidgets.QFrame(self.Notifications_3)
        self.line_6.setGeometry(QtCore.QRect(0, 230, 1001, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_28 = QtWidgets.QLabel(self.Notifications_3)
        self.label_28.setGeometry(QtCore.QRect(0, 240, 281, 51))
        self.label_28.setStyleSheet("font-size:18px;\n"
"font-weight:bold;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.Notifications_3)
        self.label_29.setGeometry(QtCore.QRect(0, 280, 841, 51))
        self.label_29.setStyleSheet("font-size:14px;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_29.setObjectName("label_29")
        self.line_7 = QtWidgets.QFrame(self.Notifications_3)
        self.line_7.setGeometry(QtCore.QRect(0, 330, 1001, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.label_30 = QtWidgets.QLabel(self.Notifications_3)
        self.label_30.setGeometry(QtCore.QRect(0, 350, 171, 51))
        self.label_30.setStyleSheet("font-size:18px;\n"
"font-weight:bold;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.Notifications_3)
        self.label_31.setGeometry(QtCore.QRect(0, 400, 841, 51))
        self.label_31.setStyleSheet("font-size:14px;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_31.setObjectName("label_31")
        self.tabWidget.addTab(self.Notifications_3, "")
        self.Security_3 = QtWidgets.QWidget()
        self.Security_3.setObjectName("Security_3")
        self.label_32 = QtWidgets.QLabel(self.Security_3)
        self.label_32.setGeometry(QtCore.QRect(0, 20, 341, 51))
        self.label_32.setStyleSheet("font-size:18px;\n"
"font-weight:bold;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.Security_3)
        self.label_33.setGeometry(QtCore.QRect(10, 60, 481, 51))
        self.label_33.setStyleSheet("font-size:14px;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_33.setObjectName("label_33")
        self.comboBox_2 = QtWidgets.QComboBox(self.Security_3)
        self.comboBox_2.setGeometry(QtCore.QRect(50, 120, 31, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.Security_3)
        self.comboBox_3.setGeometry(QtCore.QRect(90, 120, 61, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.line_8 = QtWidgets.QFrame(self.Security_3)
        self.line_8.setGeometry(QtCore.QRect(0, 160, 1001, 16))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.label_34 = QtWidgets.QLabel(self.Security_3)
        self.label_34.setGeometry(QtCore.QRect(0, 170, 341, 51))
        self.label_34.setStyleSheet("font-size:18px;\n"
"font-weight:bold;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.Security_3)
        self.label_35.setGeometry(QtCore.QRect(10, 210, 481, 51))
        self.label_35.setStyleSheet("font-size:14px;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.Security_3)
        self.label_36.setGeometry(QtCore.QRect(10, 250, 501, 51))
        self.label_36.setStyleSheet("font-size:14px;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_36.setObjectName("label_36")
        self.line_9 = QtWidgets.QFrame(self.Security_3)
        self.line_9.setGeometry(QtCore.QRect(0, 300, 1001, 16))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.label_37 = QtWidgets.QLabel(self.Security_3)
        self.label_37.setGeometry(QtCore.QRect(0, 310, 341, 51))
        self.label_37.setStyleSheet("font-size:18px;\n"
"font-weight:bold;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.Security_3)
        self.label_38.setGeometry(QtCore.QRect(0, 350, 481, 51))
        self.label_38.setStyleSheet("font-size:14px;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.Security_3)
        self.label_39.setGeometry(QtCore.QRect(0, 390, 481, 51))
        self.label_39.setStyleSheet("font-size:14px;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.Security_3)
        self.label_40.setGeometry(QtCore.QRect(0, 430, 481, 51))
        self.label_40.setStyleSheet("font-size:14px;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.Security_3)
        self.label_41.setGeometry(QtCore.QRect(0, 470, 481, 51))
        self.label_41.setStyleSheet("font-size:14px;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_41.setObjectName("label_41")
        self.line_10 = QtWidgets.QFrame(self.Security_3)
        self.line_10.setGeometry(QtCore.QRect(0, 520, 1001, 16))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.label_42 = QtWidgets.QLabel(self.Security_3)
        self.label_42.setGeometry(QtCore.QRect(0, 530, 341, 51))
        self.label_42.setStyleSheet("font-size:18px;\n"
"font-weight:bold;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.Security_3)
        self.label_43.setGeometry(QtCore.QRect(0, 570, 481, 51))
        self.label_43.setStyleSheet("font-size:14px;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_43.setObjectName("label_43")
        self.tabWidget.addTab(self.Security_3, "")
        self.Account_3 = QtWidgets.QWidget()
        self.Account_3.setObjectName("Account_3")
        self.widget = QtWidgets.QWidget(self.Account_3)
        self.widget.setGeometry(QtCore.QRect(230, 80, 521, 471))
        self.widget.setStyleSheet("border:1px solid #0000;")
        self.widget.setObjectName("widget")
        self.Emailfield_4 = QtWidgets.QLineEdit(self.widget)
        self.Emailfield_4.setGeometry(QtCore.QRect(120, 230, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Emailfield_4.setFont(font)
        self.Emailfield_4.setStyleSheet("border:1px solid black;\n"
"padding:10px")
        self.Emailfield_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Emailfield_4.setObjectName("Emailfield_4")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(100, 40, 341, 51))
        self.label_8.setStyleSheet("font-size:20px;\n"
"font-weight:bold;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_8.setObjectName("label_8")
        self.Emailfield_2 = QtWidgets.QLineEdit(self.widget)
        self.Emailfield_2.setGeometry(QtCore.QRect(120, 170, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Emailfield_2.setFont(font)
        self.Emailfield_2.setStyleSheet("border:1px solid black;\n"
"padding:10px;")
        self.Emailfield_2.setObjectName("Emailfield_2")
        self.Emailfield_6 = QtWidgets.QLineEdit(self.widget)
        self.Emailfield_6.setGeometry(QtCore.QRect(120, 290, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Emailfield_6.setFont(font)
        self.Emailfield_6.setStyleSheet("border:1px solid black;\n"
"padding:10px;")
        self.Emailfield_6.setObjectName("Emailfield_6")
        self.backtologinbtn = QtWidgets.QPushButton(self.widget)
        self.backtologinbtn.setGeometry(QtCore.QRect(120, 350, 291, 40))
        self.backtologinbtn.setStyleSheet("background:black;\n"
"color:#fff;\n"
"border:1px solid black;\n"
"font-weight:bold;\n"
"font-size:14px;")
        self.backtologinbtn.setObjectName("backtologinbtn")
        self.backtologinbtn.clicked.connect(self.update_account)
        self.Emailfield = QtWidgets.QLineEdit(self.widget)
        self.Emailfield.setGeometry(QtCore.QRect(120, 110, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Emailfield.setFont(font)
        self.Emailfield.setStyleSheet("border:1px solid black;\n"
"padding:10px;")
        self.Emailfield.setObjectName("Emailfield")
        self.tabWidget.addTab(self.Account_3, "")
        self.About_3 = QtWidgets.QWidget()
        self.About_3.setObjectName("About_3")
        self.label_56 = QtWidgets.QLabel(self.About_3)
        self.label_56.setGeometry(QtCore.QRect(700, 150, 291, 51))
        self.label_56.setStyleSheet("font-size:15px;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.About_3)
        self.label_57.setGeometry(QtCore.QRect(0, 150, 291, 51))
        self.label_57.setStyleSheet("font-size:15px;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_57.setObjectName("label_57")
        self.label_60 = QtWidgets.QLabel(self.About_3)
        self.label_60.setGeometry(QtCore.QRect(0, 90, 251, 51))
        self.label_60.setStyleSheet("font-size:15px;\n"
"font-weight:bold;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.About_3)
        self.label_61.setGeometry(QtCore.QRect(330, 90, 291, 51))
        self.label_61.setStyleSheet("font-size:15px;\n"
"font-weight:bold;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_61.setObjectName("label_61")
        self.label_64 = QtWidgets.QLabel(self.About_3)
        self.label_64.setGeometry(QtCore.QRect(670, 90, 331, 51))
        self.label_64.setStyleSheet("font-size:15px;\n"
"font-weight:bold;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(self.About_3)
        self.label_65.setGeometry(QtCore.QRect(330, 150, 291, 51))
        self.label_65.setStyleSheet("font-size:15px;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.About_3)
        self.label_66.setGeometry(QtCore.QRect(0, 20, 481, 51))
        self.label_66.setStyleSheet("font-size:15px;\n"
"font-weight:bold;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_66.setObjectName("label_66")
        self.label_58 = QtWidgets.QLabel(self.About_3)
        self.label_58.setGeometry(QtCore.QRect(0, 190, 291, 51))
        self.label_58.setStyleSheet("font-size:15px;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_58.setObjectName("label_58")
        self.label_68 = QtWidgets.QLabel(self.About_3)
        self.label_68.setGeometry(QtCore.QRect(0, 230, 261, 21))
        self.label_68.setStyleSheet("font-size:10px;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_68.setObjectName("label_68")
        self.tabWidget.addTab(self.About_3, "")
        # self.setCentralWidget(self.centralwidget)
        # self.menubar = QtWidgets.QMenuBar(classificationwindow)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 1096, 22))
        # self.menubar.setObjectName("menubar")
        # self.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(classificationwindow)
        # self.statusbar.setObjectName("statusbar")
        # self.setStatusBar(self.statusbar)

        self.retranslateUi(self)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, classificationwindow):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("classificationwindow", "MainWindow"))
        # self.pushButton.setText(_translate("classificationwindow", "ACTIVATE SUBSCRIPTION"))
        # self.pushButton_2.setText(_translate("classificationwindow", "BUY NOW"))
        self.label_7.setText(_translate("classificationwindow", "SETTING"))
        self.label_14.setText(_translate("classificationwindow", "Application Updates"))
        self.label_15.setText(_translate("classificationwindow", "Automatically download and start Updates"))
        self.pushButton_5.setText(_translate("classificationwindow", "Check for updates"))
        self.label_16.setText(_translate("classificationwindow", "Windows Exproler Setting"))
        self.label_17.setText(_translate("classificationwindow", "Add Malx Options to Window Explroler"))
        self.label_18.setText(_translate("classificationwindow", "Usage and Threat Statistics"))
        self.label_19.setText(_translate("classificationwindow", "Help fight malware by providing usage and threat statistics"))
        self.label_20.setText(_translate("classificationwindow", "View Privacy Policy"))
        self.label_21.setText(_translate("classificationwindow", "Proxy Server"))
        self.label_22.setText(_translate("classificationwindow", "Configure Malx to connect to the internet using a proxy server"))
        self.pushButton_6.setText(_translate("classificationwindow", "Restore Default Setting"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.General_3), _translate("classificationwindow", "General"))
        self.label_23.setText(_translate("classificationwindow", "Notifications"))
        self.label_24.setText(_translate("classificationwindow", "Show a monthly security Summary"))
        self.label_25.setText(_translate("classificationwindow", "Show all notifications in windows notifications area"))
        self.label_26.setText(_translate("classificationwindow", "Hide Notification when sechduled scan complete without threat detacted"))
        self.comboBox.setItemText(0, _translate("classificationwindow", "5 seconds"))
        self.comboBox.setItemText(1, _translate("classificationwindow", "7 seconds"))
        self.comboBox.setItemText(2, _translate("classificationwindow", "9 seconds"))
        self.comboBox.setItemText(3, _translate("classificationwindow", "11 seconds"))
        self.label_27.setText(_translate("classificationwindow", "Close non critical notifications after"))
        self.label_28.setText(_translate("classificationwindow", "Marketing Prefrences"))
        self.label_29.setText(_translate("classificationwindow", "Show Promotional Notifications from Malx"))
        self.label_30.setText(_translate("classificationwindow", "Play Mode"))
        self.label_31.setText(_translate("classificationwindow", "Suspend Notifications and updates when selected apps are open"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Notifications_3), _translate("classificationwindow", "Notifications"))
        self.label_32.setText(_translate("classificationwindow", "Update threat intelligence"))
        self.label_33.setText(_translate("classificationwindow", "Automatically check for threat intelligence updates"))
        self.comboBox_2.setItemText(0, _translate("classificationwindow", "1"))
        self.comboBox_2.setItemText(1, _translate("classificationwindow", "2"))
        self.comboBox_2.setItemText(2, _translate("classificationwindow", "3"))
        self.comboBox_2.setItemText(3, _translate("classificationwindow", "4"))
        self.comboBox_2.setItemText(4, _translate("classificationwindow", "5"))
        self.comboBox_3.setItemText(0, _translate("classificationwindow", "Minutes"))
        self.comboBox_3.setItemText(1, _translate("classificationwindow", "Hours"))
        self.comboBox_3.setItemText(2, _translate("classificationwindow", "Days"))
        self.label_34.setText(_translate("classificationwindow", "Update threat intelligence"))
        self.label_35.setText(_translate("classificationwindow", "Automatically quarantine malware upon detection"))
        self.label_36.setText(_translate("classificationwindow", "Automatically unquarantine when detected malware is false positive"))
        self.label_37.setText(_translate("classificationwindow", "Scan Options"))
        self.label_38.setText(_translate("classificationwindow", "Scan for rootkit"))
        self.label_39.setText(_translate("classificationwindow", "Scan within archive"))
        self.label_40.setText(_translate("classificationwindow", "Use aritifical intelligence to detect threat "))
        self.label_41.setText(_translate("classificationwindow", "Use expert system algorithm to indentify malicious file"))
        self.label_42.setText(_translate("classificationwindow", "Windows Security Centers"))
        self.label_43.setText(_translate("classificationwindow", "Always register malx in the windows security centers"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Security_3), _translate("classificationwindow", "Security"))
        self.Emailfield_4.setPlaceholderText(_translate("classificationwindow", "Password"))
        self.label_8.setText(_translate("classificationwindow", "Update Your Account info"))
        self.Emailfield_2.setPlaceholderText(_translate("classificationwindow", "Enter Email"))
        self.Emailfield_6.setPlaceholderText(_translate("classificationwindow", "Phone"))
        self.backtologinbtn.setText(_translate("classificationwindow", "UPDATE"))
        self.Emailfield.setPlaceholderText(_translate("classificationwindow", "Enter Name"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Account_3), _translate("classificationwindow", "Account"))
        self.label_56.setText(_translate("classificationwindow", "1.0.2613"))
        self.label_57.setText(_translate("classificationwindow", "4.6.4.286"))
        self.label_60.setText(_translate("classificationwindow", "MALX VERSION"))
        self.label_61.setText(_translate("classificationwindow", "UPDATE PACKAGE VERSION"))
        self.label_64.setText(_translate("classificationwindow", "COMPONENT PACKAGE VERSION"))
        self.label_65.setText(_translate("classificationwindow", "1.0.76295"))
        self.label_66.setText(_translate("classificationwindow", "Version Information"))
        self.label_58.setText(_translate("classificationwindow", "Check for updates"))
        self.label_68.setText(_translate("classificationwindow", "Last Updated:10/17/2023         7:53pm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.About_3), _translate("classificationwindow", "About"))
from qrc import source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
#     classificationwindow = QtWidgets.QMainWindow()
    ui = Ui_settings(app)
#     classificationwindow.resize(1100,900)
#     ui.setupUi(classificationwindow)
    ui.show()
    sys.exit(app.exec_())
