# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import typing
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget
from qrc import source_rc
from my_header import HeaderWidget
class Ui_settings(QtWidgets.QWidget):
    def __init__(self, parent):
        super().__init__()
        self.main_window=parent
        self.setupUi()


    def setupUi(self):
        # classificationwindow.setObjectName("classificationwindow")
        self.resize(1096, 916)
        # classificationwindow.setStyleSheet("background:white !important;")
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        # self.centralwidget.resize(1096, 916)
        self.header=HeaderWidget(self.main_window,self.centralwidget)
        
        
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 110, 1181, 821))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1179, 819))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.tabWidget = QtWidgets.QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget.setGeometry(QtCore.QRect(50, 80, 1001, 721))
        self.tabWidget.setObjectName("tabWidget")
        self.General = QtWidgets.QWidget()
        self.General.setObjectName("General")
        self.label_8 = QtWidgets.QLabel(self.General)
        self.label_8.setGeometry(QtCore.QRect(10, 20, 261, 51))
        self.label_8.setStyleSheet("font-size:18px;\n"
"font-weight:bold;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.General)
        self.label_9.setGeometry(QtCore.QRect(10, 60, 481, 51))
        self.label_9.setStyleSheet("font-size:14px;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_9.setObjectName("label_9")
        self.pushButton_3 = QtWidgets.QPushButton(self.General)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 110, 161, 41))
        self.pushButton_3.setStyleSheet("background:white;\n"
"color:#00000;\n"
"border:1px solid black;\n"
"font-weight:bold;\n"
"font-size:14px;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.line = QtWidgets.QFrame(self.General)
        self.line.setGeometry(QtCore.QRect(0, 180, 991, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_10 = QtWidgets.QLabel(self.General)
        self.label_10.setGeometry(QtCore.QRect(10, 200, 321, 51))
        self.label_10.setStyleSheet("font-size:18px;\n"
"font-weight:bold;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.General)
        self.label_11.setGeometry(QtCore.QRect(10, 250, 321, 51))
        self.label_11.setStyleSheet("font-size:18px;\n"
"font-weight:bold;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.General)
        self.label_12.setGeometry(QtCore.QRect(160, 330, 321, 51))
        self.label_12.setStyleSheet("font-size:18px;\n"
"font-weight:bold;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.General)
        self.label_13.setGeometry(QtCore.QRect(170, 440, 321, 51))
        self.label_13.setStyleSheet("font-size:18px;\n"
"font-weight:bold;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.General)
        self.label_14.setGeometry(QtCore.QRect(50, 500, 321, 51))
        self.label_14.setStyleSheet("font-size:18px;\n"
"font-weight:bold;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.General)
        self.label_15.setGeometry(QtCore.QRect(210, 570, 321, 51))
        self.label_15.setStyleSheet("font-size:18px;\n"
"font-weight:bold;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_15.setObjectName("label_15")
        self.tabWidget.addTab(self.General, "")
        self.Notifications = QtWidgets.QWidget()
        self.Notifications.setObjectName("Notifications")
        self.tabWidget.addTab(self.Notifications, "")
        self.Security = QtWidgets.QWidget()
        self.Security.setObjectName("Security")
        self.tabWidget.addTab(self.Security, "")
        self.Display = QtWidgets.QWidget()
        self.Display.setObjectName("Display")
        self.tabWidget.addTab(self.Display, "")
        self.AllowList = QtWidgets.QWidget()
        self.AllowList.setObjectName("AllowList")
        self.tabWidget.addTab(self.AllowList, "")
        self.Account = QtWidgets.QWidget()
        self.Account.setObjectName("Account")
        self.tabWidget.addTab(self.Account, "")
        self.About = QtWidgets.QWidget()
        self.About.setObjectName("About")
        self.tabWidget.addTab(self.About, "")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setGeometry(QtCore.QRect(20, 10, 201, 51))
        self.label_7.setStyleSheet("font-size:20px;\n"
"font-weight:bold;\n"
"line-height:40px;\n"
"margin:0px auto;\n"
"text-align:center;\n"
"")
        self.label_7.setObjectName("label_7")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        # classificationwindow.setCentralWidget(self.centralwidget)
        # self.menubar = QtWidgets.QMenuBar(self)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 1096, 22))
        # self.menubar.setObjectName("menubar")
        # # classificationwindow.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(self)
        # self.statusbar.setObjectName("statusbar")
        # classificationwindow.setStatusBar(self.statusbar)

        self.retranslateUi(self)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, classificationwindow):
        _translate = QtCore.QCoreApplication.translate
        classificationwindow.setWindowTitle(_translate("classificationwindow", "MainWindow"))
        self.label_8.setText(_translate("classificationwindow", "Application Updates"))
        self.label_9.setText(_translate("classificationwindow", "Automatically download and start Updates"))
        self.pushButton_3.setText(_translate("classificationwindow", "Check for updates"))
        self.label_10.setText(_translate("classificationwindow", "Windows Exproler Setting"))
        self.label_11.setText(_translate("classificationwindow", "Windows Exproler Setting"))
        self.label_12.setText(_translate("classificationwindow", "Windows Exproler Setting"))
        self.label_13.setText(_translate("classificationwindow", "Windows Exproler Setting"))
        self.label_14.setText(_translate("classificationwindow", "Windows Exproler Setting"))
        self.label_15.setText(_translate("classificationwindow", "Windows Exproler Setting"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.General), _translate("classificationwindow", "General"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Notifications), _translate("classificationwindow", "Notifications"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Security), _translate("classificationwindow", "Security"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Display), _translate("classificationwindow", "Display"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.AllowList), _translate("classificationwindow", "Allow List"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Account), _translate("classificationwindow", "Account"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.About), _translate("classificationwindow", "About"))
        self.label_7.setText(_translate("classificationwindow", "SETTING"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
#     classificationwindow = QtWidgets.QMainWindow()
    ui = Ui_settings(app)
    ui.show()
#     ui.setupUi(classificationwindow)
#     classificationwindow.show()
    sys.exit(app.exec_())
